version: 2
updates:
  - package-ecosystem: gradle
    directory: /backend
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /analyzers/ts-analyzer
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /analyzers/tree-analyzer
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
